export const FETCH_ALL_PHONES_START = 'FETCH_ALL_PHONES_START';
export const FETCH_ALL_PHONES_SUCCESS = 'FETCH_ALL_PHONES_SUCCESS';
export const FETCH_ALL_PHONES_FAILURE = 'FETCH_ALL_PHONES_FAILURE';

export const LOAD_MORE_PHONES_START = 'LOAD_MORE_PHONES_START';
export const LOAD_MORE_PHONES_SUCCESS = 'LOAD_MORE_PHONES_SUCCESS';
export const LOAD_MORE_PHONES_FAILURE = 'LOAD_MORE_PHONES_FAILURE';

export const FETCH_PHONE_START = 'FETCH_PHONE_START';
export const FETCH_PHONE_SUCCESS = 'FETCH_PHONE_SUCCESS';
export const FETCH_PHONE_FAILURE = 'FETCH_PHONE_FAILURE';

export const ADD_PHONE_TO_BASKET = 'ADD_PHONE_TO_BASKET';

export const REMOVE_PHONE_FROM_BASKET = 'REMOVE_PHONE_FROM_BASKET';

export const CLEAN_BASKET = 'CLEAN_BASKET';