export const FETCH_ALL_PHONES_START = 'FETCH_ALL_PHONES_START';
export const FETCH_ALL_PHONES_SUCCESS = 'FETCH_ALL_PHONES_SUCCESS';
export const FETCH_ALL_PHONES_FAILURE = 'FETCH_ALL_PHONES_FAILURE';

export const LOAD_MORE_PHONES_START = 'LOAD_MORE_PHONES_START';
export const LOAD_MORE_PHONES_SUCCESS = 'LOAD_MORE_PHONES_SUCCESS';
export const LOAD_MORE_PHONES_FAILURE = 'LOAD_MORE_PHONES_FAILURE';